const fs=require("fs");const path=require("path");const crypto=require("crypto");const config=require("./config");const {validate,loadRelation}=require("./arquivos");const {createDocument,getDocument,signDocument,signerIsSigned,downloadSignedPdf,listRecentProductionDocuments,matchProductionDocument}=require("./autentique");const {getProduction,getSandbox,markProcessing,markSent,markError}=require("./storage");const {acquire}=require("./lock");
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let stopping=false,releaseLock=null,reconciliationCache=null;
function parseLimit(){const arg=process.argv.slice(3).find(x=>x.startsWith("--limite="));if(!arg)return undefined;const n=Number(arg.split("=")[1]);if(!Number.isInteger(n)||n<1)throw new Error("--limite deve ser um inteiro maior que zero.");return n;}
function hasFlag(f){return process.argv.slice(3).includes(f);} function header(t){console.log("\n"+"=".repeat(60)+`\n ${t}\n`+"=".repeat(60));} function logLine(m){const l=`[${new Date().toISOString()}] ${m}`;console.log(l);try{fs.mkdirSync("dados",{recursive:true});fs.appendFileSync("dados/envio.log",l+"\n");}catch{}}
function sha256(f){return new Promise((res,rej)=>{const h=crypto.createHash("sha256"),s=fs.createReadStream(f);s.on("data",d=>h.update(d));s.on("error",rej);s.on("end",()=>res(h.digest("hex")));});}
async function reconcile(item,force=false){if(!reconciliationCache||force){logLine("Reconciliando documentos recentes na Autentique...");reconciliationCache=await listRecentProductionDocuments();logLine(`Reconciliação carregada: ${reconciliationCache.length} documentos.`);}return matchProductionDocument(reconciliationCache,item);}
async function send(mode,limit,dryRun){const items=validate(),state=mode==="sandbox"?getSandbox():getProduction(),sent=new Set(Object.keys(state.enviados)),pending=items.filter(x=>!sent.has(x.fileName.toLowerCase())),batch=limit?pending.slice(0,limit):pending;header(dryRun?"DRY-RUN":mode==="sandbox"?"ENVIO SANDBOX":"ENVIO PRODUÇÃO");console.log(`Total na relação: ${items.length}\nJá registrados: ${sent.size}\nPendentes: ${pending.length}\nNesta execução: ${batch.length}`);if(dryRun){batch.forEach((x,i)=>console.log(`${i+1}. ${x.fileName} → ${x.email}`));return;}if(!batch.length){console.log("\nNada pendente.");return;}
for(let i=0;i<batch.length;i++){if(stopping)break;const item=batch[i],k=item.fileName.toLowerCase();logLine(`----- ${i+1}/${batch.length} ${item.fileName} → ${item.email} -----`);let success=false;
for(let attempt=1;attempt<=config.maxRetries&&!stopping;attempt++){try{const now=mode==="sandbox"?getSandbox():getProduction();let id=now.processando?.[k]?.documentId||null;if(id)logLine(`Retomando checkpoint: ${id}`);
if(!id&&mode==="production"){const existing=await reconcile(item,attempt>1);if(existing){id=existing.id;logLine(`Documento reconciliado antes da criação: ${id}`);markProcessing(mode,item,id);}}
let fresh=false;if(!id){const doc=await createDocument(item,mode==="sandbox");id=doc.id;fresh=true;logLine(`${mode==="sandbox"?"SANDBOX CRIADO":"ENVIADO"}: ${id}`);markProcessing(mode,item,id);if(mode==="production"&&reconciliationCache)reconciliationCache.unshift({id,name:item.fileName.replace(/\.pdf$/i,""),created_at:new Date().toISOString(),signatures:[{email:config.signerEmail},{email:item.email}]});}
// Para documento recém-criado, o ID e os signatários já são conhecidos: assina diretamente.
// Em retomada, uma consulta verifica se a assinatura já aconteceu antes de repetir a mutação.
if(fresh){logLine(`Assinando automaticamente com ${config.signerEmail}...`);await signDocument(id);}else{const doc=await getDocument(id);if(!signerIsSigned(doc,config.signerEmail)){logLine(`Assinando automaticamente com ${config.signerEmail}...`);await signDocument(id);}else logLine(`Assinatura de ${config.signerEmail} já estava confirmada.`);}
const result=await downloadSignedPdf(id,item.fileName,true);const sourceHash=await sha256(path.join(config.sourceDir,item.fileName));markSent(mode,item,id,{signedPdf:{size:result.size,sha256:result.sha256},sourcePdfSha256:sourceHash});logLine(`Concluído: ${result.path} | ${result.size} bytes | SHA-256 ${result.sha256}`);success=true;break;
}catch(err){logLine(`ERRO tentativa ${attempt}: ${err.message}`);if(attempt<config.maxRetries&&!stopping){const wait=config.retryBaseMs*attempt;logLine(`Aguardando ${wait/1000}s...`);await sleep(wait);}else if(!stopping)markError(mode,item,err);}}
if(success&&i<batch.length-1&&!stopping){await sleep(config.delayMs);}}
console.log(stopping?"\nExecução interrompida com segurança após a etapa atual.":"\nExecução concluída.");}
function showStatus(){const items=loadRelation(),p=getProduction(),s=getSandbox();header("STATUS");console.log(`Total na relação: ${items.length}\nProdução — enviados/confirmados: ${Object.keys(p.enviados).length}\nProdução — em processamento: ${Object.keys(p.processando||{}).length}\nProdução — erros: ${Object.keys(p.erros).length}\nProdução — pendentes: ${items.length-Object.keys(p.enviados).length}\nSandbox — testes registrados: ${Object.keys(s.enviados).length}`);}
function installSignals(){const stop=()=>{if(!stopping){stopping=true;logLine("Ctrl+C recebido. Não serão iniciados novos documentos; aguardando a etapa atual terminar.");}else{logLine("Segundo Ctrl+C: encerramento forçado.");releaseLock?.();process.exit(130);}};process.on("SIGINT",stop);process.on("SIGTERM",stop);}
async function main(){const command=process.argv[2];try{if(command==="validar"){header("VALIDAÇÃO");validate();console.log("\nPronto para teste Sandbox ou envio real.");return;}if(command==="status"){showStatus();return;}const dryRun=hasFlag("--dry-run");if(!["teste","enviar"].includes(command)){console.log("Comandos: npm run validar | npm run teste -- --limite=1 | npm run enviar -- --limite=1 | npm run enviar | npm run status");return;}if(!dryRun){releaseLock=acquire();installSignals();}await send(command==="teste"?"sandbox":"production",parseLimit()||(command==="teste"?1:undefined),dryRun);}catch(err){console.error("\nERRO:",err.message);process.exitCode=1;}finally{releaseLock?.();}}main();
